### ISSUE TITLE
Boxplots for predicted FA_Dur, SP_ROC, all Peak_Dur, all Peak_Fre are split into two

### ISSUE THREAD

**Issue by kristaniguchi** [ceff-tech/ffc_api_client#49] opened 2020-03-04 18:45 UTC
Boxplots for predicted FA_Dur, SP_ROC, all Peak_Dur, all Peak_Fre are split into two. Please plot only one boxplot for those predicted metrics
![Peak_Fre](https://user-images.githubusercontent.com/10887520/75912631-607f6d80-5e06-11ea-87f0-dd183491acf1.png)

**Comment by nickrsan** [comment] 2020-03-04 19:27
Huh - I haven't seen this behavior - I see the COMID you used there, but am not sure if this is a gage, or using your own timeseries - was this when using the data/code you sent me previously, or something else? Just wondering so I can reproduce it and figure out where the bug is.

**Comment by kristaniguchi** [comment] 2020-03-04 20:22
Yes, using the code i sent you and my own gage data for observed ffcAPIClient::evaluate_alteration()

**Comment by nickrsan** [comment] 2020-03-11 21:23
OK, traced this problem to a data issue from the flows API related to the predicted flow metrics producing duplicate values. I'm going to have it deduplicate, but it's not an exact process because sometimes the values are different.

**Comment by nickrsan** [comment] 2020-03-11 21:24
As an addendum, this probably only showed up recently because we used to use internal data that we'd deduplicated, but we switched to the flow API about a month ago. I'm in touch with Kirk about it too in case they want to address it themselves - I reported it to Ted last year.

**Comment by nickrsan** [comment] 2020-03-11 21:42
OK, resolved this issue in commit a7fd8671fe28af1fded1d0dc390c00c330da8b6b

Kris, whenever you get a chance, can you upgrade and let me know if you encounter this issue or any new errors? I'm closing it for now, but please reopen it if a related bug still exists.

**Closed as completed by nickrsan** 2020-03-11 21:42 UTC

**Comment by kristaniguchi** [comment] 2020-03-20 17:18
Thanks, Nick!  Works great.

Kris

--
Kris Taniguchi-Quan, PhD
Scientist
Southern California Coastal Water Research Project
3535 Harbor Blvd, Suite 110<https://maps.google.com/?q=3535+Harbor+Blvd,+Suite+110+%0D%0A+Costa+Mesa,+CA+92626+%0D%0A+Office:+(714&entry=gmail&source=g>
Costa Mesa, CA 92626<https://maps.google.com/?q=3535+Harbor+Blvd,+Suite+110+%0D%0A+Costa+Mesa,+CA+92626+%0D%0A+Office:+(714&entry=gmail&source=g>
Office: 714<https://maps.google.com/?q=3535+Harbor+Blvd,+Suite+110+%0D%0A+Costa+Mesa,+CA+92626+%0D%0A+Office:+(714&entry=gmail&source=g>-755-3221
kristinetq@sccwrp.org<mailto:kristinetq@sccwrp.org>
www.sccwrp.org<http://www.sccwrp.org/>

SCCWRP’s response to COVID-19: Read the full statement<https://www.sccwrp.org/sccwrp-response-to-covid-19>
